Repository hashicorp/packer-plugin-googlecompute, pull requests merged in 2022-06, with the labels that each got.

#96 Remove unneeded Sprintf
  builder/googlecompute/step_start_tunnel_test.go
Labels: technical-debt

#84 Migrate to new Google Cloud impersonation API
  builder/googlecompute/builder.go
  builder/googlecompute/config.go
  builder/googlecompute/driver_gce.go
  builder/googlecompute/step_import_os_login_ssh_key.go
  builder/googlecompute/step_wait_startup_script.go
  docs-partials/post-processor/googlecompute-export/Config-not-required.mdx
  docs-partials/post-processor/googlecompute-import/Config-not-required.mdx
  post-processor/googlecompute-export/post-processor.go
  post-processor/googlecompute-export/post-processor.hcl2spec.go
  post-processor/googlecompute-import/post-processor.go
  post-processor/googlecompute-import/post-processor.hcl2spec.go
Labels: enhancement

#94 Added support for node affinity labels
  builder/googlecompute/config.go
  builder/googlecompute/config.hcl2spec.go
  builder/googlecompute/config_test.go
  builder/googlecompute/driver.go
  builder/googlecompute/driver_gce.go
  builder/googlecompute/step_create_instance.go
  docs-partials/builder/googlecompute/Config-not-required.mdx
  docs-partials/builder/googlecompute/NodeAffinity-not-required.mdx
  docs-partials/builder/googlecompute/NodeAffinity.mdx
  docs-partials/builder/googlecompute/NodeAffinityConfig-not-required.mdx
  docs-partials/builder/googlecompute/NodeAffinityConfig.mdx
Labels: enhancement

#101 .github: stop ignoring dependabot commits on release
  .github/release.yml
Labels: ignore-for-release
